/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.FillDetailscontroller;
import database.DbConnection;
import model.FillDetailmodel;

/**
 *
 * @author Kiran
 */
public class Filldetails extends javax.swing.JFrame {

    /**
     * Creates new form fillDetails
     */
    public Filldetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qw = new javax.swing.JLabel();
        qwe = new javax.swing.JLabel();
        qwer = new javax.swing.JLabel();
        Contactno = new javax.swing.JLabel();
        Lcn = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Middle_Name = new javax.swing.JTextField();
        Location_ = new javax.swing.JTextField();
        Contact_no = new javax.swing.JTextField();
        First_Name = new javax.swing.JTextField();
        Last_Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        qw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qw.setText("First Name :");

        qwe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qwe.setText("Middle Name:");

        qwer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qwer.setText("Last Name : ");

        Contactno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Contactno.setText("Contact Number :");

        Lcn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lcn.setText("Location :");

        Save.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Save.setText("Save");
        Save.setBorder(null);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setBorder(null);

        Middle_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Location_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Contact_no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        First_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Last_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qw)
                    .addComponent(qwe)
                    .addComponent(Lcn)
                    .addComponent(qwer)
                    .addComponent(Contactno))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Middle_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Location_, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(Contact_no)
                    .addComponent(First_Name)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancel)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qw)
                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Middle_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qwe))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qwer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Location_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lcn))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contactno))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Save))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
// TODO add your handling code here:
        String FirstName=First_Name.getText();
        String MiddleName=Middle_Name.getText();
        String LastName=Last_Name.getText();
        String Location=Location_.getText();
        String ContactNo=Contact_no.getText();
        FillDetailmodel model=new FillDetailmodel(FirstName,MiddleName,LastName,Location,ContactNo);
        FillDetailscontroller FillDetail=new FillDetailscontroller();
        FillDetail.insertFillDetailmodel(model);
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filldetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField Contact_no;
    private javax.swing.JLabel Contactno;
    private javax.swing.JTextField First_Name;
    private javax.swing.JTextField Last_Name;
    private javax.swing.JLabel Lcn;
    private javax.swing.JTextField Location_;
    private javax.swing.JTextField Middle_Name;
    private javax.swing.JButton Save;
    private javax.swing.JLabel qw;
    private javax.swing.JLabel qwe;
    private javax.swing.JLabel qwer;
    // End of variables declaration//GEN-END:variables
}
