/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.ForgotPasswordcontroller;
import javax.swing.JOptionPane;
import model.ForgotPasswordmodel;

/**
 *
 * @author Kiran
 */
public class ForgotPassword extends javax.swing.JFrame {

    public static String getentername() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public static String getentercontact() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public static String getentermessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Email_ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Continue = new javax.swing.JButton();
        NewPw = new javax.swing.JTextField();
        LastPw = new javax.swing.JTextField();
        ConfirmPw = new javax.swing.JTextField();
        Pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 30, 176, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Email :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 116, 64, -1));

        Email_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_ActionPerformed(evt);
            }
        });
        getContentPane().add(Email_, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 221, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Last Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 218, 128, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("New Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 116, 134, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Confirm New Password :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 218, -1, -1));

        Continue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        getContentPane().add(Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 371, -1, -1));

        NewPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPwActionPerformed(evt);
            }
        });
        getContentPane().add(NewPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 159, 202, -1));
        getContentPane().add(LastPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 282, 202, -1));
        getContentPane().add(ConfirmPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 282, 202, -1));

        Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/login.jpg"))); // NOI18N
        getContentPane().add(Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_ActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        // TODO add your handling code here:
        String Email=Email_.getText();
        String LastPassword=LastPw.getText();
        String NewPassword=NewPw.getText();
        String ConfirmPassword=ConfirmPw.getText();
        if(NewPassword==ConfirmPassword){
            ForgotPasswordmodel model=new ForgotPasswordmodel(Email,LastPassword,NewPassword,ConfirmPassword);
            ForgotPasswordcontroller ForgotPassword=new ForgotPasswordcontroller();
            ForgotPassword.insertForgotPasswordmodel(model);
        }
        if(NewPassword!=ConfirmPassword){
                        JOptionPane.showMessageDialog(null,"Password does not match");

        }
        else{
            JOptionPane.showMessageDialog(null,"Please fill all the input fields...");
        }
    }//GEN-LAST:event_ContinueActionPerformed

    private void NewPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfirmPw;
    private javax.swing.JButton Continue;
    private javax.swing.JTextField Email_;
    private javax.swing.JTextField LastPw;
    private javax.swing.JTextField NewPw;
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
